name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  nocterm:
    path: ../../../

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.6
